### PR TITLE
Fixes bones not being unbroken on admin rejuv

### LINKED ISSUE #1138: Aheal doesn't restore broken bones
Round ID: None, local test server

Reproduction:
- Get Broken bones anywhere
- Admin Rejuvenate yourself
- See how your bones are still broken

Picture of proof: 
aheal bones

### PR DESCRIPTION
**Pull request by AffectedArc07**
## About The Pull Request
Fixes #1138 

This PR will make it so using admin heal will force heal every bone in the body

## Why It's Good For The Game
Admin healing someone should fix their damn bones

## Changelog
:cl:
fix: Admin revives now heal broken bones
/:cl:

### CODE REVIEW

**Comment by Birdtalon** [comment]
Is it not just better to include this under `regenerate_limbs()`?

**Comment by AffectedArc07** [comment]
@Birdtalon good spot, now bones will be fixed if a ling regens too.

**Comment by Sikroth** [comment]
Not particularly important but since I saw the chem while code diving, will adminordrazine cure broken bones?

**Comment by Birdtalon** [comment]
```/datum/reagent/medicine/adminordrazine/on_mob_life(mob/living/carbon/M)
	M.reagents.remove_all_type(/datum/reagent/toxin, 5*REM, 0, 1)
	M.setCloneLoss(0, 0)
	M.setOxyLoss(0, 0)
	M.radiation = 0
	M.heal_bodypart_damage(5,5)
	M.adjustToxLoss(-5, 0, TRUE)
	M.hallucination = 0
	M.setOrganLoss(ORGAN_SLOT_BRAIN, 0)
	REMOVE_TRAITS_NOT_IN(M, list(SPECIES_TRAIT, ROUNDSTART_TRAIT, ORGAN_TRAIT))
	M.set_blurriness(0)
	M.set_blindness(0)
	M.SetKnockdown(0, 0)
	M.SetStun(0, 0)
	M.SetUnconscious(0, 0)
	M.silent = FALSE
	M.dizziness = 0
	M.disgust = 0
	M.drowsyness = 0
	M.stuttering = 0
	M.slurring = 0
	M.confused = 0
	M.SetSleeping(0, 0)
	M.jitteriness = 0
	M.cure_all_traumas(TRAUMA_RESILIENCE_MAGIC)
	if(M.blood_volume < (BLOOD_VOLUME_NORMAL*M.blood_ratio))
		M.blood_volume = (BLOOD_VOLUME_NORMAL*M.blood_ratio)

	for(var/organ in M.internal_organs)
		var/obj/item/organ/O = organ
		O.setOrganDamage(0)

	for(var/thing in M.diseases)
		var/datum/disease/D = thing
		if(D.severity == DISEASE_SEVERITY_POSITIVE)
			continue
		D.cure()
	..()
	. = 1
```
@Sikroth by the looks of it no.

**Pull request merged**
