### PR TITLE
Oracle UI

### PR DESCRIPTION
**Pull request by Alonefromhell**
## About The Pull Request
Ports https://github.com/OracleStation/OracleStation/pull/702 which gives us the ability to make some very neat and *self-updating* UI's.

## Why It's Good For The Game
usability and neatage.

## Changelog
:cl:
add: Ported Oracle UI, a framework for self-updating and neat UI's
refactor: Paper now uses OUI
refactor: Bins now use OUI
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Please put the files for this under `modular_kepler`

**Comment by Alonefromhell** [comment]
> 
> 
> Please put the files for this under `modular_kepler`

Done.

**Comment by AffectedArc07** [comment]
```
loading tgstation.mdme
tgstation.mdme:2276:error: unable to open "code/modules/oracle_ui/assets.dm".
tgstation.mdme:2277:error: unable to open "code/modules/oracle_ui/hookup_procs.dm".
tgstation.mdme:2278:error: unable to open "code/modules/oracle_ui/oracle_ui.dm".
tgstation.mdme:2279:error: unable to open "code/modules/oracle_ui/themed.dm".
```

**Comment by AffectedArc07** [comment]
Travis seems broken

**Comment by AffectedArc07** [comment]
It works on my PC without the file not found
image

Probably due to linux relative pathing, requiring `./` at the start of the paths

**Comment by AffectedArc07** [comment]
Ok so its just travis that hates it, it starts fine when running on regular linux
https://gist.github.com/AffectedArc07/46d2c8c37eca482d7366bbe04742b784

Just add a check for travis testing to make it not render

**Pull request merged**
