### PR TITLE
Renames pockets

### PR DESCRIPTION
**Pull request by Alonefromhell**
## About The Pull Request
Does what it says in the title.
billede

## Why It's Good For The Game
Imagine calling a pocket for `storage1`. pff.

## Changelog
:cl:
spellcheck: Pockets have been renamed. They actually make IC sense now.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Does this also show pocket name in the strip menu?

**Comment by Alonefromhell** [comment]
This doesn't change that, no. It'll still say `left` or `right` in the strip menu.

**Comment by AffectedArc07** [comment]
Are you sure left and right are mapped correctly?

**Comment by AffectedArc07** [comment]
image
If this is wrong I swear to god

**Pull request merged**
