### PR TITLE
[PORT] Public autolathes for everyone 

### PR DESCRIPTION
**Pull request by Alonefromhell**
## About The Pull Request
Makes sure there is at least one autolathe on Box, Delta and Meta.
port of https://github.com/Citadel-Station-13/Citadel-Station-13/pull/8819

## Why It's Good For The Game
Public lathes for everyone

## Changelog
:cl:
add: Box, Delta and Meta now has at least one public autolathe.
/:cl:

### CODE REVIEW

**Comment by Shadeykins** [comment]
Not sure how I feel about public autolathes since they're easy printers for people who don't typically have much business with these items. Them being hackable means they're also cheap ammo dispensers for antagonists.

Will wait for input from Corn/Affected, but I see this as causing more problems than it solves down the road.

**Comment by Alonefromhell** [comment]
That's fine. It was done on request from affected, so i don't have an opinion either way.

**Comment by AffectedArc07** [comment]
I want it in, but purely because of keeping in sync with upstream. Ideally we want to be kept in sync with Citadel as close as possible, but to be fair this is a minor edit and we have already tweaked the maps to remove ***certain*** things.

**Comment by Alonefromhell** [comment]
Closing, because i don't think it's needed. It would also lessen interaction with cargo people.

**Pull request closed without merging**
