### PR TITLE
Slime changes

### PR DESCRIPTION
**Pull request by CornMyCob**
## About The Pull Request

Updates the slime person mob sprite to paradise's and also adds a species variable to make their body's transparent. I'd preferably like to make the colours show the same as paradise too, once I figure out how that's handled. Currently there's one bug with this PR, which is that the hands do not respect the transparent variable for some reason.

## Why It's Good For The Game

Slimes are slightly less ugly now.

## Changelog
:cl:
add: Transparency variable in species code
tweak: Slimes are less ugly now
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
I remember @Ziiro had an issue like this when he was porting IPCs to oracle, one of the limbs wasn’t following the vars of the others. Try asking him for what the fix is

**Comment by Ziiro** [comment]
It appears that I have been summoned.

>Currently there's one bug with this PR, which is that the hands do not respect the transparent variable for some reason.

That's.. weird. The hands? Or the entire arm? Do you have a screenshot of this behavior? Wonder if it has something to do with clothing overlays/glove options.

**Comment by Sishen1542** [comment]
> It appears that I have been summoned.
> 
> > Currently there's one bug with this PR, which is that the hands do not respect the transparent variable for some reason.
> 
> That's.. weird. The hands? Or the entire arm? Do you have a screenshot of this behavior? Wonder if it has something to do with clothing overlays/glove options.

Been trying to fix it myself. Here's an image of the hands.

**Comment by AffectedArc07** [comment]
image
This may be of use

**Comment by Poojawa** [comment]
Hands aren't real body parts. they're just an Aux layered image attached to arms. 

Everything you do with arm parts needs to be applied to 'aux' parts as well.

**Comment by AffectedArc07** [comment]
Made it work 
image

**Pull request merged**
